//var baseurl = 'http://35.166.195.23:8080/ApiGateway/';
//var baseurl = 'https://engage-staging.quantifiedcare.com/ApiGateway/';
//var baseurl = 'https://192.168.0.24:8080/ApiGateway/';
var baseurl ='https://34.203.9.235/ApiGateway/'
var pathwaymicroservice = 'pathway';
var pathwayapibase = baseurl + pathwaymicroservice;
var usermicroservice = 'users';
var userapibase = baseurl + usermicroservice;
var patientmicroservice = 'patient';
var patientapibase = baseurl + patientmicroservice;
var schedulermicroservice = 'scheduled';
var schedulerapibase = baseurl + schedulermicroservice;