var baseurl = 'https://engage-staging.quantifiedcare.com/ApiGateway/';
var pathwaymicroservice = 'pathway';
var pathwayapibase = baseurl + pathwaymicroservice;
var usermicroservice = 'users';
var userapibase = baseurl + usermicroservice;
var patientmicroservice = 'patient';
var patientapibase = baseurl + patientmicroservice;
var schedulermicroservice = 'scheduled';
var schedulerapibase = baseurl + schedulermicroservice;
